name: Sentinel CI Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sentinel-check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Sentinel Check
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -m cli.main check --json
      
      # NOTE: sentinel check exits with code 1 if any golden trace fails
      # This will fail the CI build if there are regressions
